#!/usr/bin/env bash
# Generated by tools/make_unix_launchers.py - edit the .bat and re-run.
set -euo pipefail
cd "$(dirname "$0")"
PY=.venv/bin/python

# No argument = your account. An argument = that named account, e.g.
#   ./run_all.command spouse   ->  --config config.spouse.json
CFG=""
if [ "${1:-}" != "" ]; then CFG="--config config.$1.json"; fi

if [ ! -x "$PY" ]; then
    echo "This app is not set up yet - run ./setup.command first."
    exit 1
fi

echo '============================================================'
echo 'Gap Receipts - sign in'
echo '============================================================'
echo 'A normal Chromium window will open. Then:'
echo '1. Sign in to your Gap / Gap Inc. account (handle any OTP / puzzle yourself)'
echo '2. Open your Order History and confirm you see your orders'
echo '3. LEAVE THAT BROWSER WINDOW OPEN - do not close it'

"$PY" gap_receipts.py --open-browser $CFG
