#!/usr/bin/env bash
# Generated by tools/make_unix_launchers.py - edit the .bat and re-run.
set -euo pipefail
cd "$(dirname "$0")"
PY=.venv/bin/python

# No argument = your account. An argument = that named account, e.g.
#   ./run_all.command spouse   ->  --config config.spouse.json
CFG=""
if [ "${1:-}" != "" ]; then CFG="--config config.$1.json"; fi

echo "============================================================"
echo "Wealthfront Documents - sign in"
echo "============================================================"
echo "A normal Chromium window will open. Then:"
echo "1. Sign in to Wealthfront (do the 2FA yourself)"
echo "2. Open your Documents / Statements page"
echo "3. LEAVE THAT BROWSER WINDOW OPEN - do not close it"

"$PY" wealthfront_docs.py --open-browser $CFG
