#!/usr/bin/env bash
# Generated by tools/make_unix_launchers.py - edit the .bat and re-run.
set -euo pipefail
cd "$(dirname "$0")"
PY=.venv/bin/python

# No argument = your account. An argument = that named account, e.g.
#   ./login.command spouse   ->  --config config.spouse.json
CFG=""
if [ "${1:-}" != "" ]; then CFG="--config config.$1.json"; fi

if [ ! -x "$PY" ]; then
    echo "This app is not set up yet - run ./setup.command first."
    exit 1
fi

echo '============================================================'
echo 'UPS Documents - sign in'
echo '============================================================'
echo 'Your own Edge or Chrome will open, with a separate profile. Then:'
echo '1. Sign in to ups.com yourself, including any code it sends'
echo '2. LEAVE THAT BROWSER WINDOW OPEN - do not close it'
echo '3. Then run:  paperpull ups pilot   (the five newest documents)'
echo 'READ-ONLY: this tool only downloads your UPS invoice PDFs. It NEVER'

"$PY" ups_docs.py --open-browser $CFG
