#!/usr/bin/env bash
# Generated by tools/make_unix_launchers.py - edit the .bat and re-run.
set -euo pipefail
cd "$(dirname "$0")"
PY=.venv/bin/python

# No argument = your account. An argument = that named account, e.g.
#   ./login.command spouse   ->  --config config.spouse.json
CFG=""
if [ "${1:-}" != "" ]; then CFG="--config config.$1.json"; fi

if [ ! -x "$PY" ]; then
    echo "This app is not set up yet - run ./setup.command first."
    exit 1
fi

echo '============================================================'
echo 'Apple Receipts - sign in'
echo '============================================================'
echo 'A browser window will open on Report a Problem'
echo '1. Sign in there, and answer any code Apple sends yourself'
echo '2. For Apple Store orders, open apple.com/shop/order/list in a second'
echo 'tab and sign in there too. It is a separate sign-in'
echo '3. LEAVE THAT BROWSER WINDOW OPEN, do not close it'

"$PY" apple_receipts.py --open-browser $CFG
