#!/usr/bin/env bash
# Generated by tools/make_unix_launchers.py - edit the .bat and re-run.
set -euo pipefail
cd "$(dirname "$0")"
PY=.venv/bin/python

# No argument = your account. An argument = that named account, e.g.
#   ./run_all.command spouse   ->  --config config.spouse.json
CFG=""
if [ "${1:-}" != "" ]; then CFG="--config config.$1.json"; fi

echo "Read-only inspection of the Navy Federal documents page. Downloads NOTHING"
echo "Make sure you are signed in and your documents page is open"

"$PY" navyfederal_docs.py --diagnose $CFG
