#!/usr/bin/env bash
# Generated by tools/make_unix_launchers.py - edit the .bat and re-run.
set -euo pipefail
cd "$(dirname "$0")"
PY=.venv/bin/python

# No argument = your account. An argument = that named account, e.g.
#   ./run_all.command spouse   ->  --config config.spouse.json
CFG=""
if [ "${1:-}" != "" ]; then CFG="--config config.$1.json"; fi

echo "FULL download of Navy Federal statements, tax forms, and insurance documents"
echo "Make sure that account's signed-in browser is still OPEN"

"$PY" navyfederal_docs.py --all $CFG
