#!/usr/bin/env bash
# Generated by tools/make_unix_launchers.py - edit the .bat and re-run.
set -euo pipefail
cd "$(dirname "$0")"
PY=.venv/bin/python

# No argument = your account. An argument = that named account, e.g.
#   ./login.command spouse   ->  --config config.spouse.json
CFG=""
if [ "${1:-}" != "" ]; then CFG="--config config.$1.json"; fi

if [ ! -x "$PY" ]; then
    echo "This app is not set up yet - run ./setup.command first."
    exit 1
fi

echo '============================================================'
echo 'American Family Documents - sign in'
echo '============================================================'
echo 'Your own Edge or Chrome will open, with a separate profile. Then:'
echo '1. Sign in to American Family (do all the 2FA / device approval yourself)'
echo '2. Open your Statements & Documents page (Accounts, then Statements & Documents)'
echo '3. LEAVE THAT BROWSER WINDOW OPEN - do not close it'

"$PY" amfam_docs.py --open-browser $CFG
