#!/usr/bin/env bash
# Generated by tools/make_unix_launchers.py - edit the .bat and re-run.
set -euo pipefail
cd "$(dirname "$0")"
PY=.venv/bin/python

# No argument = your account. An argument = that named account, e.g.
#   ./login.command spouse   ->  --config config.spouse.json
CFG=""
if [ "${1:-}" != "" ]; then CFG="--config config.$1.json"; fi

if [ ! -x "$PY" ]; then
    echo "This app is not set up yet - run ./setup.command first."
    exit 1
fi

echo '============================================================'
echo 'Costco Receipts - sign in'
echo '============================================================'
echo 'A browser window will open. Then:'
echo '1. Sign in to your Costco account (handle any code or passkey yourself)'
echo '2. Open Orders ^& Purchases and confirm you can see your purchases'
echo '3. LEAVE THAT BROWSER WINDOW OPEN - do not close it'
echo '4. Run:  paperpull costco record   and click your way to one receipt'

"$PY" costco_receipts.py --open-browser $CFG
