#!/usr/bin/env bash
# Generated by tools/make_unix_launchers.py - edit review_names.bat and re-run.
set -euo pipefail
cd "$(dirname "$0")"

# No argument = your account. An argument = that named account, e.g.
#   ./review_names.command spouse   ->  --config config.spouse.json
CFG=""
if [ "${1:-}" != "" ]; then CFG="--config config.$1.json"; fi

echo '============================================================'
echo 'Costco Receipts - review names'
echo '============================================================'
echo 'Goes through the receipts whose names the app was unsure of, one at a'
echo 'time. Type a better name, press Enter to keep the one it has, or type'
echo 'q to stop. Each name you type renames its PDF, and the spreadsheets'
echo 'follow.'
echo

# This folder's own Python when ./setup.command made one. A folder the
# PaperPull app made has no setup.command, and runs on the app's own Python.
PY=.venv/bin/python
if [ ! -x "$PY" ]; then
    if [ -f setup.command ]; then
        echo "This app is not set up yet - run ./setup.command first."
        exit 1
    fi
    PY=""
    for APP in /Applications/PaperPull.app "$HOME/Applications/PaperPull.app"; do
        if [ -x "$APP/Contents/Resources/python/bin/python3" ]; then
            PY="$APP/Contents/Resources/python/bin/python3"
            break
        fi
    done
    if [ -z "$PY" ]; then
        echo "PaperPull was not found in Applications. If it is somewhere else, run"
        echo "  <that folder>/PaperPull.app/Contents/Resources/paperpull costco review-names"
        exit 1
    fi
    # As the app itself runs it. Nothing from your own Python setup, and
    # bytecode in your cache, never inside the app.
    export PYTHONNOUSERSITE=1
    export PYTHONPYCACHEPREFIX="$HOME/Library/Caches/PaperPull/pycache"
fi

"$PY" costco_receipts.py --review-names $CFG
