#!/usr/bin/env bash
# Generated by tools/make_unix_launchers.py - edit the .bat and re-run.
set -euo pipefail
cd "$(dirname "$0")"
PY=.venv/bin/python

# No argument = your account. An argument = that named account, e.g.
#   ./run_all.command spouse   ->  --config config.spouse.json
CFG=""
if [ "${1:-}" != "" ]; then CFG="--config config.$1.json"; fi

if [ ! -x "$PY" ]; then
    echo "This app is not set up yet - run ./setup.command first."
    exit 1
fi

echo '============================================================'
echo 'U.S. Bank Documents - sign in'
echo '============================================================'
echo 'READ-ONLY: downloads card statements. It never pays a bill, transfers a'
echo 'balance, redeems rewards, or changes a setting. Run diagnose any time'
echo 'for a safe look - it reads the page and downloads nothing'
echo 'Your Edge or Chrome will open. Sign in to U.S. Bank yourself (all 2FA),'
echo 'then open Statements and documents - and LEAVE THAT WINDOW OPEN'

"$PY" usbank_docs.py --open-browser $CFG
