#!/usr/bin/env bash
# Generated by tools/make_unix_launchers.py - edit the .bat and re-run.
set -euo pipefail
cd "$(dirname "$0")"
PY=.venv/bin/python

# No argument = your account. An argument = that named account, e.g.
#   ./login.command spouse   ->  --config config.spouse.json
CFG=""
if [ "${1:-}" != "" ]; then CFG="--config config.$1.json"; fi

if [ ! -x "$PY" ]; then
    echo "This app is not set up yet - run ./setup.command first."
    exit 1
fi

echo '============================================================'
echo 'Fidelity Documents - sign in'
echo '============================================================'
echo 'A browser window will open on fidelity.com. Then:'
echo '1. Sign in to Fidelity yourself, including the two-factor prompt'
echo '2. Open your statements or messages area if you know where it is'
echo '3. LEAVE THAT BROWSER WINDOW OPEN - do not close it'
echo '4. Then run:  paperpull fidelity diagnose   (a safe look, downloads nothing)'

"$PY" fidelity_docs.py --open-browser $CFG
