"""Generate macOS/Linux launchers alongside the Windows .bat files.

The .bat files stay the source of truth for *what* each launcher does; this
mirrors them into `.command` scripts, which macOS runs on double-click. Only
setup and login remain as launchers, and review_names in the receipt apps,
which asks for a name at a time and so cannot run in the panel. Everything
else is `paperpull <app> <command>` (see paperpull.py), the same on every
platform.

git on Windows cannot record that a file is executable, so a .command
generated there reaches a Mac without it and will not open on a
double-click. After generating on Windows, run
`git update-index --chmod=+x` on every new .command. A test refuses one
that is not executable.

    python tools/make_unix_launchers.py

Re-run after adding an app or changing a launcher.
"""
from __future__ import annotations

import re
import stat
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
APPS = REPO / "apps"

HEADER = """#!/usr/bin/env bash
# Generated by tools/make_unix_launchers.py - edit the .bat and re-run.
set -euo pipefail
cd "$(dirname "$0")"
PY=.venv/bin/python

# No argument = your account. An argument = that named account, e.g.
#   ./login.command spouse   ->  --config config.spouse.json
CFG=""
if [ "${1:-}" != "" ]; then CFG="--config config.$1.json"; fi

if [ ! -x "$PY" ]; then
    echo "This app is not set up yet - run ./setup.command first."
    exit 1
fi
"""

SETUP = """#!/usr/bin/env bash
# Generated by tools/make_unix_launchers.py - edit setup.bat and re-run.
set -euo pipefail
cd "$(dirname "$0")"

echo "=== {provider} setup ==="

PY3="$(command -v python3 || true)"
if [ -z "$PY3" ]; then
    echo "Python 3 was not found. Install it from https://www.python.org/downloads/"
    echo "or with Homebrew:  brew install python"
    exit 1
fi
echo "Using Python: $PY3"

"$PY3" -m venv .venv
.venv/bin/python -m pip install --upgrade pip
.venv/bin/pip install -r requirements.txt

# The shared core: a repo checkout has it two levels up; a standalone install
# ships a vendored wheel in core/.
if [ -f "../../core/pyproject.toml" ]; then
    .venv/bin/pip install -e ../../core
else
    .venv/bin/pip install core/paperpull_core-*.whl
fi

# The 400 MB browser download is NOT part of setup. Any Chromium-based
# browser already installed can be used. If none is found, login offers
# the download then, when somebody is present to agree to it.

echo
echo "Setup complete. Next step: ./login.command and sign in to {provider}."
"""

# review_names runs in a checkout, like the others, and also in a folder the
# PaperPull app made, which has no .venv and no setup.command and runs on
# the Python inside the app. So it is not HEADER plus a line. @TITLE@ is the
# banner already shell-quoted, @SCRIPT@ the entry script, @SLUG@ the app's
# folder name for the terminal command it offers when the app is not found.
REVIEW = """#!/usr/bin/env bash
# Generated by tools/make_unix_launchers.py - edit review_names.bat and re-run.
set -euo pipefail
cd "$(dirname "$0")"

# No argument = your account. An argument = that named account, e.g.
#   ./review_names.command spouse   ->  --config config.spouse.json
CFG=""
if [ "${1:-}" != "" ]; then CFG="--config config.$1.json"; fi

echo '============================================================'
echo @TITLE@
echo '============================================================'
echo 'Goes through the receipts whose names the app was unsure of, one at a'
echo 'time. Type a better name, press Enter to keep the one it has, or type'
echo 'q to stop. Each name you type renames its PDF, and the spreadsheets'
echo 'follow.'
echo

# This folder's own Python when ./setup.command made one. A folder the
# PaperPull app made has no setup.command, and runs on the app's own Python.
PY=.venv/bin/python
if [ ! -x "$PY" ]; then
    if [ -f setup.command ]; then
        echo "This app is not set up yet - run ./setup.command first."
        exit 1
    fi
    PY=""
    for APP in /Applications/PaperPull.app "$HOME/Applications/PaperPull.app"; do
        if [ -x "$APP/Contents/Resources/python/bin/python3" ]; then
            PY="$APP/Contents/Resources/python/bin/python3"
            break
        fi
    done
    if [ -z "$PY" ]; then
        echo "PaperPull was not found in Applications. If it is somewhere else, run"
        echo "  <that folder>/PaperPull.app/Contents/Resources/paperpull @SLUG@ review-names"
        exit 1
    fi
    # As the app itself runs it. Nothing from your own Python setup, and
    # bytecode in your cache, never inside the app.
    export PYTHONNOUSERSITE=1
    export PYTHONPYCACHEPREFIX="$HOME/Library/Caches/PaperPull/pycache"
fi

"$PY" @SCRIPT@ --review-names $CFG
"""

REVIEW_SCRIPT_RE = re.compile(r'"%PY%"\s+(\S+\.py)\s+--review-names')
REVIEW_TITLE_RE = re.compile(r"^echo\s+(.+? - review names)\s*$", re.M)


def windows_to_unix(text: str) -> str:
    """A macOS user should never be told to run a .bat file."""
    return re.sub(r"\b([A-Za-z_]+)\.bat\b", r"./\1.command", text)


def shell_quote(text: str) -> str:
    """Single-quote for bash, so quotes, backticks and $ in a .bat's echo text
    stay literal instead of being re-interpreted - or executed - when the
    generated script runs."""
    return "'" + text.replace("'", "'" + chr(92) + "''") + "'"


ACTION_RE = re.compile(r"python\.exe\s+(\S+\.py)\s+(--[\w-]+)", re.I)


def build(app_dir: Path) -> list:
    made = []
    for bat in sorted(app_dir.glob("*.bat")):
        text = bat.read_text(encoding="utf-8", errors="ignore")
        if bat.name == "setup.bat":
            m = re.search(r"=== (.+?) setup ===", text)
            provider = m.group(1) if m else app_dir.name.title()
            out = app_dir / "setup.command"
            out.write_text(SETUP.format(provider=provider), encoding="utf-8", newline="\n")
            made.append(out)
            continue
        if bat.name == "review_names.bat":
            script, title = REVIEW_SCRIPT_RE.search(text), REVIEW_TITLE_RE.search(text)
            if not (script and title):
                raise SystemExit("%s does not read the way review_names.bat does" % bat)
            out = app_dir / "review_names.command"
            out.write_text(REVIEW.replace("@TITLE@", shell_quote(title.group(1).strip()))
                                 .replace("@SCRIPT@", script.group(1))
                                 .replace("@SLUG@", app_dir.name),
                           encoding="utf-8", newline="\n")
            made.append(out)
            continue
        m = ACTION_RE.search(text)
        if not m:
            continue
        script, flag = m.group(1), m.group(2)
        notes = [e.strip().rstrip(".") for e in re.findall(r"^echo (.+)$", text, re.M)]
        banner = "\n".join(f"echo {shell_quote(windows_to_unix(n))}"
                           for n in notes[:8]
                           if n and "%" not in n and n != ".")
        out = app_dir / (bat.stem + ".command")
        out.write_text(HEADER + "\n" + banner + "\n\n"
                       + f'"$PY" {script} {flag} $CFG\n',
                       encoding="utf-8", newline="\n")
        made.append(out)
    for f in made:
        f.chmod(f.stat().st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)
    return made


def main() -> None:
    total = 0
    for app_dir in sorted(p for p in APPS.iterdir() if p.is_dir()):
        made = build(app_dir)
        total += len(made)
        print(f"  {app_dir.name:12} {len(made)} launcher(s)")
    print(f"\n{total} launcher(s) generated.")


if __name__ == "__main__":
    main()
