"""Generate macOS/Linux launchers alongside the Windows .bat files.

The .bat files stay the source of truth for *what* each launcher does; this
mirrors them into `.command` scripts, which macOS runs on double-click. Every
app gets the same actions under the same names, so the docs and the muscle
memory carry across platforms.

    python tools/make_unix_launchers.py

Re-run after adding an app or changing a launcher.
"""
from __future__ import annotations

import re
import stat
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
APPS = REPO / "apps"

HEADER = """#!/usr/bin/env bash
# Generated by tools/make_unix_launchers.py - edit the .bat and re-run.
set -euo pipefail
cd "$(dirname "$0")"
PY=.venv/bin/python

# No argument = your account. An argument = that named account, e.g.
#   ./run_all.command spouse   ->  --config config.spouse.json
CFG=""
if [ "${1:-}" != "" ]; then CFG="--config config.$1.json"; fi
"""

SETUP = """#!/usr/bin/env bash
# Generated by tools/make_unix_launchers.py - edit setup.bat and re-run.
set -euo pipefail
cd "$(dirname "$0")"

echo "=== {provider} setup ==="

PY3="$(command -v python3 || true)"
if [ -z "$PY3" ]; then
    echo "Python 3 was not found. Install it from https://www.python.org/downloads/"
    echo "or with Homebrew:  brew install python"
    exit 1
fi
echo "Using Python: $PY3"

"$PY3" -m venv .venv
.venv/bin/python -m pip install --upgrade pip
.venv/bin/pip install -r requirements.txt

# The shared core: a repo checkout has it two levels up; a standalone install
# ships a vendored wheel in core/.
if [ -f "../../core/pyproject.toml" ]; then
    .venv/bin/pip install -e ../../core
else
    .venv/bin/pip install core/paperpull_core-*.whl
fi

.venv/bin/python -m playwright install chromium

echo
echo "Setup complete. Next step: ./login.command and sign in to {provider}."
"""

ACTION_RE = re.compile(r"python\.exe\s+(\S+\.py)\s+(--[\w-]+)", re.I)


def build(app_dir: Path) -> list:
    made = []
    for bat in sorted(app_dir.glob("*.bat")):
        text = bat.read_text(encoding="utf-8", errors="ignore")
        if bat.name == "setup.bat":
            m = re.search(r"=== (.+?) setup ===", text)
            provider = m.group(1) if m else app_dir.name.title()
            out = app_dir / "setup.command"
            out.write_text(SETUP.format(provider=provider), encoding="utf-8", newline="\n")
            made.append(out)
            continue
        m = ACTION_RE.search(text)
        if not m:
            continue
        script, flag = m.group(1), m.group(2)
        notes = [e.strip().rstrip(".") for e in re.findall(r"^echo (.+)$", text, re.M)]
        banner = "\n".join(f'echo "{n}"' for n in notes[:8]
                           if n and "%" not in n and n != ".")
        out = app_dir / (bat.stem + ".command")
        out.write_text(HEADER + "\n" + banner + "\n\n"
                       + f'"$PY" {script} {flag} $CFG\n',
                       encoding="utf-8", newline="\n")
        made.append(out)
    for f in made:
        f.chmod(f.stat().st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)
    return made


def main() -> None:
    total = 0
    for app_dir in sorted(p for p in APPS.iterdir() if p.is_dir()):
        made = build(app_dir)
        total += len(made)
        print(f"  {app_dir.name:12} {len(made)} launcher(s)")
    print(f"\n{total} launcher(s) generated.")


if __name__ == "__main__":
    main()
