#!/usr/bin/env bash
# Generated by tools/make_unix_launchers.py - edit the .bat and re-run.
set -euo pipefail
cd "$(dirname "$0")"
PY=.venv/bin/python

# No argument = your account. An argument = that named account, e.g.
#   ./login.command spouse   ->  --config config.spouse.json
CFG=""
if [ "${1:-}" != "" ]; then CFG="--config config.$1.json"; fi

if [ ! -x "$PY" ]; then
    echo "This app is not set up yet - run ./setup.command first."
    exit 1
fi

echo '============================================================'
echo 'Uber Receipts - sign in'
echo '============================================================'
echo 'A browser window will open on your Uber trips'
echo '1. Sign in there, and answer any code Uber sends yourself'
echo '2. For Uber Eats orders, open ubereats.com/orders in a second tab'
echo 'and sign in there too. It is a separate sign-in'
echo '3. LEAVE THAT BROWSER WINDOW OPEN, do not close it'

"$PY" uber_receipts.py --open-browser $CFG
