#!/usr/bin/env bash
# Generated by tools/make_unix_launchers.py - edit the .bat and re-run.
set -euo pipefail
cd "$(dirname "$0")"
PY=.venv/bin/python

# No argument = your account. An argument = that named account, e.g.
#   ./login.command spouse   ->  --config config.spouse.json
CFG=""
if [ "${1:-}" != "" ]; then CFG="--config config.$1.json"; fi

if [ ! -x "$PY" ]; then
    echo "This app is not set up yet - run ./setup.command first."
    exit 1
fi

echo '============================================================'
echo 'Apple Card Documents - sign in'
echo '============================================================'
echo 'Your own Edge or Chrome will open, with a separate profile. Then:'
echo '1. Sign in to card.apple.com (do all the 2FA / device approval yourself)'
echo '2. Stay on card.apple.com once you are in'
echo '3. LEAVE THAT BROWSER WINDOW OPEN - do not close it'
echo '4. Then press Record in the panel, or run:  paperpull applecard record'

"$PY" applecard_docs.py --open-browser $CFG
